kendoctor_admin_user:
    resource: "@KendoctorAppBundle/Resources/config/routing/admin/user.yml"
    prefix: /user

kendoctor_admin_group:
    resource: "@KendoctorAppBundle/Resources/config/routing/admin/group.yml"
    prefix: /group

kendoctor_admin_project:
    resource: "@KendoctorAppBundle/Resources/config/routing/admin/project.yml"
    prefix: /project

