<?php

namespace Kendoctor\Bundle\AppBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param $criteria
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function createIndexQueryBuilder($criteria)
    {
        $qb = $this->createQueryBuilder('o');


        return $qb;
    }

    public function getById($id)
    {
        $qb = $this->createQueryBuilder('o');

        $qb
            ->where('o.id = :id')
            ->setParameter('id' , $id)
        ;
        return $qb->getQuery()->getOneOrNullResult();
    }
}
